### ISSUE TITLE
Module Fails to Initialize at `new Session()`

### ISSUE THREAD

**Issue by cartergloria37** [sessionjs/client#2]
#### Description
Module fails to initialize when creating a new `Session()` object, raising an error related to undefined `options.proxy`.

#### Steps to Reproduce
1. Set up everything as described in the Getting Started guide.
2. Use the following code:
   ```javascript
	import express from 'express';
	import { Session, ready } from '@session.js/client'
	
	// Ensure the library and dependencies are ready
	await ready;
	
	session = new Session();
   ```
3. Run the server:
   ```bash
   bun run server.ts
   ```

4. The following error is produced:
   ```bash
   $ bun run server.ts
   28 |     }
   29 | }
   30 | export class BunNetwork {
   31 |     proxy;
   32 |     constructor(options) {
   33 |         this.proxy = options.proxy && (typeof options.proxy === 'string'
                            ^
   TypeError: undefined is not an object (evaluating 'options.proxy')
         at new BunNetwork (/home/user/Projects/session-bot-new/node_modules/@session.js/bun-network/dist/index.js:33:22)
         at new Session (/home/user/Projects/session-bot-new/node_modules/@session.js/client/dist/instance/index.js:46:32)
         at /home/user/Projects/session-bot-new/server.ts:18:11

   Bun v1.1.26 (Linux x64)
   ```

#### Expected Behavior
The session should initialize successfully without any errors.

#### Actual Behavior
The initialization fails, throwing a `TypeError: undefined is not an object (evaluating 'options.proxy')`.

#### Environment Details:
- **Node Manager**: Bun v1.1.26 (Linux x64)
- **Module**: `@session.js/bun-network`
- **File causing the error**: `node_modules/@session.js/bun-network/dist/index.js` at line 33

#### Additional Notes
- This issue seems to be related to the proxy configuration within the `BunNetwork` class.
- Steps were followed exactly as per the Getting Started guide, and no additional proxy configuration was mentioned.

#### Possible Solution
It seems like the `options` object passed into the constructor of `BunNetwork` might be `undefined`, or the `proxy` property is missing. A check for the existence of `options` should likely be implemented here:

```javascript
this.proxy = options?.proxy && (typeof options.proxy === 'string');
```

Thank you for looking into this issue!

**Comment by VityaSchel** [comment]
Thank you for reporting that and for using session.js! I'm aware of this issue and it's because code expects options object in constructor to be present. Please for now just pass {} in argument as in new Session({})
I'm having troubles right now with money so I don't have time to work on session.js, but this will be definitely fixed in the urgent manner as soon as I come back to work on it. I'm sorry for inconvenience!

**Comment by cartergloria37** [comment]
invoking new Session({});

didnt worked, same error.

**Comment by VityaSchel** [comment]
Can you update @session.js/client to 0.0.47, try again and let me know if it now works?

**Comment by cartergloria37** [comment]
hmm, same issue

**Comment by cartergloria37** [comment]
ok, worked now!
thank you!

**Comment by cartergloria37** [comment]
can you share your xmr address so i can tip you?

**Comment by VityaSchel** [comment]
You can find it there: https://hloth.dev/donate
Thank you for support!

**Comment by cartergloria37** [comment]
sent 40$
